### ISSUE TITLE
Update Name Instances

### ISSUE THREAD

**Issue by wtheisen** [wtheisen/TerminusBrowser#61]
Due to our recent name change we need to update all the instances of the old name and IRC channel in the docs and code! This should be really easy to do and would be a great beginner PR!!

**Comment by wtheisen** [comment]
The readme has been updated now, however the figlet displayed on the welcome screen hasn't been changed yet! @AndroidKitKat

**Comment by AndroidKitKat** [comment]
I'll take a look. Easy enough to do at work probably.

**Comment by sambattalio** [comment]
Thanks for taking charge of this akk! Very impressive to see your dedication.

**Comment by wtheisen** [comment]
uhhhhh we need an 'r' now :-)
