### ISSUE TITLE
Option for subreddit and 4chan page removal

### ISSUE THREAD

**Issue by camicarballo** [wtheisen/TerminusBrowser#73]
I think it would be useful to have a :remove option for subreddits, etc.

**Comment by sambattalio** [comment]
Good thought. Definitely should be added in the near future. Whoever wants to pick this up look at [this](https://github.com/wtheisen/TerminusBrowser/blob/master/src/Commands/SystemCommands.py) file to update it. Should be very similar to the :add command. You might also have to possibly add something to the [config object](https://github.com/wtheisen/TerminusBrowser/blob/master/src/Commands/SystemCommands.py) to better handle deletion.
