### ISSUE TITLE
Command Collision Error Checking/Site specific ordering

### ISSUE THREAD

**Issue by wtheisen** [wtheisen/TerminusBrowser#89]
### Issue and Steps to Reproduce
Currently it's possible for two command sets for different sites to have the same commands. This will cause an issue of one command always being executed due to that sites processing being done first. For example it's reasonable that both 4chan and reddit might have a command named 'Post'. It might be nice to either print an error message if there is a shared command, or conversely it should also be easy to route the command to the parser for the currently viewed site. This would be ideal as it would allowed shared commands with no collisions.

**Comment by mpernigo** [comment]
Hey! I can take a look at this, if it's still an open point

**Comment by wtheisen** [comment]
Awesome, I'd definitely start by poking around the command handler!
